name: Prettier

on:
  push:
    branches:
      - main  # or master, if that's your default branch

env:
  FILE_PATTERN: '{src,__tests__}/**/*.{ts,tsx,js,jsx}'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18  # 推奨：12 は古いです

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npx prettier --write "${FILE_PATTERN}"

      - name: Commit Prettier changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Apply Prettier formatting'
