name: Prettier

on:
  push:
    branches:
      - main  # or master, if that's your default branch

env:
  FILE_PATTERN: '{src,__tests__}/**/*.{ts,tsx,js,jsx}'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Prettier
        run: |
          npm install
          npx prettier --write "${FILE_PATTERN}"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Apply Prettier formatting'
          token: ${{ secrets.GITHUB_TOKEN }}
